DatabaseConfiguration:
  Host: Testing
  Port: 5432
  Username: user
  Password: password
  DriverName: sqlite3
  DatabaseName: ./foo.db

ServerConfiguration:
  Port: 8080

LoggingConfiguration:
  WriterType: console
  Level: DEBUG

Options:
  Testing: testing